---
- name: this on is called {{ key.os.hostname }}
  hostname:
    name: "{{ key.os.hostname }}"

- name: useradd {{ key.os.user }}
  user:
    name: "{{ key.os.user }}"
    shell: /bin/bash

 - include_role:
        name: gitarchive
      vars:
        repo: "{{ root }}"
        store: "{{ key.local.archive }}"
        target: "{{ os.mountpoint }}"
        user: "{{ key.os.user }}"

   createhome: true
