---
- name: link vendor for stash
  include_role:
    name: vendor
  vars:
    path: "{{ root }}{{ key.vendor.path }}{{ key.stash.path }}"
    mount: "{{ root }}{{ key.stash.path }}"
    executable: "{{ key.stash.vendor }}"
  
- name: link vendor for ui
  include_role:
    name: vendor
  vars:
    path: "{{ root }}{{ key.vendor.path }}{{ key.ui.path }}"
    mount: "{{ root }}{{ key.ui.path }}"
    executable: "{{ key.ui.vendor }}"
  
- name: link vendor for server
  include_role:
    name: vendor
  vars:
    path: "{{ root }}{{ key.vendor.path }}{{ key.server.path }}"
    mount: "{{ root }}{{ key.server.path }}"
    executable: "{{ key.server.vendor }}"
  
- name: link vendor for devops
  include_role:
    name: vendor
  vars:
    path: "{{ root }}{{ key.vendor.path }}{{ key.devops.path }}"
    mount: "{{ root }}{{ key.devops.path }}"
    executable: "{{ key.devops.vendor }}"
  
- include_role:
    name: postgres
  vars:
    name: "{{ key.stash.postgres.name }}"
    volume_root: "{{ root }}{{ key.data.path }}"

- include_role:
    name: redis
  vars:
    name: "{{ key.stash.redis.name }}"
    volume_root: "{{ root }}{{ key.data.path }}"
