---
- hosts: hammer

  vars:
    key: "{{ lookup('file', '../key.json') | from_json }}"
    root: "{{ playbook_dir }}/../"

  remote_user: root

  tasks:
    - include_role:
        name: node
      vars:
        envirionments:
          - "{{ root }}{{ key.ui.path }}"
          - "{{ root }}{{ key.server.path }}"
    - include_role:
        name: gitarchive
      vars:
        repo: "{{ root }}"
        store: "{{ key.local.archive }}"
        target: "{{ os.mountpoint }}"
        user: "{{ key.os.user }}"


