---
- name: infer revision from local repo
  command: git rev-parse HEAD
  register: hash
  delegate_to: localhost

- name: check deployed revision
  command: "cat {{ target }}revision"
  register: deployed_revision

- set_fact:
    hash: "{{ hash.stdout }}"
    deployed_revision: "{{ deployed_revision.stdout }}"

- include_tasks: commence.yml
  when: hash != deployed_revision
