---
- name: check if archive exists
  stat:
    path: "{{ store }}{{ hash }}.tar.gz"
  register: archive_exists

- name: create archive
  command: git archive -o {{ store }}{{ hash }}.tar.gz HEAD
  args:
    chdir: "{{ repo }}"
    creates: "{{ store }}{{ hash }}.tar.gz"
  delegate_to: localhost
  when: not archive_exists.stat.exists

- name: make way for deploy
  become: true
  become_user: "{{ user }}"
  file:
    path: "{{ target }}"
    state: directory
    recurse: true

- name: deploy and unpack
  become: true
  become_user: "{{ user }}"
  unarchive:
    src: "{{ store }}{{ hash }}.tar.gz"
    dest: "{{ target }}"

- name: put revision ({{ hash }}) in {{ target }}hash
  copy:
    content: "{{ hash }}"
    dest: "{{ target }}revision"
